Webd01/Hello-World

hello-world.r

added hello world in r

---

hello-world.m

Created the hello-world file in Objective-C

created hello-world file in Objective-C

---

hello-world.py

Hi, Please accept my PR, Thanks!

Added Hello world in Python

---

main.go

created hello-world file in gaoling

created hello-world file in Go

---

main.swift

Created hello-world in swift

---

hello-world.rockstar

Add Rockstar language https://github.com/dylanbeattie/rockstar

feat: Add Rockstar

---

hello-world.sh

Adds bash example

---

hello-world.dart

Added dart

---

Hello-world.erl
hello-world.bas
hello-world.exs
hello-world.hs

enlarge added

---

hello-world.lua

Fixes https://github.com/Webd01/Hello-World/issues/43

Added hello world in Lua

---

Hello_World.f

hello world in fortran

---

hello_world.scala

hello world in scala

---

hello-world.jl

feat: Add julia

---

README.md
hello-world.rockstar

Sorry, I've made mistake in this example, this compiles as it should.

feat: fix Rockstar syntax

---

README.md
hello-world.cob

As requested on issue #1, I added a "Hello World" in Cobol. 
To run it you have to install open-cobol.
How to run it:
```
$ cobc -xO hello-world.cob 
$ ./hello-world 
```

Add language COBOL

---

hello-world.sol

Hello there! 
This is the implementation of the Hello World in Solidity, a language used to make smart contracts on the Ethereum Blockchain.

Added Hello World in Solidity

---

README.md

As mentioned in #54  I added a new entry to the Readme file.

Updated contributors list

---

hello-world.clj

hello world -  clojure

---

HelloWorld.plsql
README.md

Added Oracle's functional language, PL/SQL.
Update readme.

Added PL/SQL

---

Hello-world.MOD

I learnt some Modula2 during evening classes at Derby Higher Education College in 1995.

feat: Modula2

---

README.md
hello-world.sql

with reference to issue #1 added sql language for hello world.

add sql language to repo

---

README.md
hello-world.cljs

Add Clojurescript

---

helloworld.coffee

Add CoffeeScript
